### ISSUE TITLE
Does not work at all in 3.0, you might as well just learn OSL (which requires Cycles)

### ISSUE THREAD

**Issue by IoIxD** [patriciogonzalezvivo/glslTexture#16]

**Comment by b4zz4** [comment]
```
Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/3.1/scripts/addons/glslTexture-master/__init__.py", line 126, in modal
    bpy.data.texts[self.source].write(self.default_code)
  File "/usr/share/blender/3.1/scripts/modules/bpy_types.py", line 772, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'GlslTexture' object has no attribute 'default_code'

location: <unknown location>:-1
```
